name: nine_slicing
description: A Flutter package that implements nine-slice scaling for images, similar to Unity engine's nine slicing feature.
version: 0.0.1
homepage: https://github.com/Simirror/nine_slicing
repository: https://gitlab.com/Simirror/nine_slicing.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  plugin:
    platforms:
      android:
        package: com.example.nine_slicing
        pluginClass: NineSlicingPlugin
      ios:
        pluginClass: NineSlicingPlugin